import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <div className="mockup-phone">
            <div className="camera"></div>
            <div className="display">
              <div className="artboard bg-white phone-5">
                <div className="phone-content">
                  {children} {/* Inserting children here */}
                </div>
              </div>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
